# Generated by Django 5.0.2 on 2024-03-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendermodel',
            name='subscribe',
            field=models.CharField(max_length=255),
        ),
    ]
