# Generated by Django 5.0.2 on 2024-03-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_alter_sendermodel_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendermodel',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
